version: '3.5'
services:
 web_dev:
  build: webapp
  ports:
   - "5000:5000"
  volumes:
   - .:/app
  environment:
   - ENV=development
   - PORT=5000
 mongodb:
  image: mongo:latest
  container_name: "mongodb"
  environment:
   - MONGO_DATA_DIR=/usr/data/db
   - MONGO_LOG_DIR=/dev/null
   - MONGO_USERNAME=chatbot
   - MONGO_PASSWORD=password
   - MONGO_INITDB_DATABASE=chatbot
  volumes:
   - ./data/db:/usr/data/db
  ports:
   - 27017:27017
  command: mongod --smallfiles --logpath=/dev/null # --quiet
networks:
 default:
  name: web_dev
